### ISSUE TITLE
Unity editor crash when adding Deformable component

### ISSUE THREAD

**Issue by tonygod** [keenanwoodall/Deform#11]
The Unity Editor crashes when I try to add a Deformer to a cube model.

I am using Unity 2018.3.10f1 on Windows 10 and verified I am using the same versions of the Packages in the package.json.

Editor log attached

[Editor.log](https://github.com/keenanwoodall/Deform/files/3046317/Editor.log)

**Comment by keenanwoodall** [comment]
I'm sorry to hear that! Does this happen consistently or was it a one-time thing?

I'm developing on the same Unity/Windows version and am not running into this problem, so I'm definitely curious as to what is causing this.

**Comment by tonygod** [comment]
It happens consistently.  I attached one of the models I have tried to use -- maybe there is something about the models I am using?  I am just trying to do a cube with 2400 verts right now.

[DeformableCube.zip](https://github.com/keenanwoodall/Deform/files/3048743/DeformableCube.zip)

Please let me know if there's other information I can provide.

**Comment by keenanwoodall** [comment]
I imported the mesh and added a deformable component to it. While it didn't crash, it did throw some errors because the mesh didn't have "Read/Write Enabled" for some reason. If it isn't enabled on your end, please enable it and see if it works.

**Comment by tonygod** [comment]
I verified Read/Write Enabled was already enabled, but I disabled, applied and re-enabled and applied and the problem still occurs.  [Here's a video clip demonstrating the problem](https://youtu.be/JFYm2g8lGv0)

**Comment by tonygod** [comment]
Here is a .unitypackage that contains the scene I am using.

1. Install Burst and Mathematics packages
2. Install Deform
3. Import MeshDeformSample.unitypackage
4. Open /Assets/00_MeshDeform/Scenes/SampleScene.unity
5. Select the "DeformableCube" GameObject in the Hierarchy
6. Click "Add Component" in the Inspector
7. Add the "Deformable" script

Result: Unity editor crash

Expected: Deformablecomponent added to DeformableCube GameObject
[MeshDeformSample.zip](https://github.com/keenanwoodall/Deform/files/3049158/MeshDeformSample.zip)

**Comment by keenanwoodall** [comment]
Just went through the steps and still no crash.

Based on the log you sent me, it seems it is crashing the moment the initial deformation work is started by the Job System in `OnEnable`. The fact that I'm using the same Unity version, Windows version _and_ scene without getting a crash makes me think the issue could actually be with the Job System.

There should be some other files in the crash folder, if you wanna send them to me I'll give them a look and see if I find anything helpful. However, at the moment I'm pretty stumped. I really want this to work for you, and I appreciate you taking the time to create and follow-up on an issue.

If I find anything I'll let you know. In the meantime you may want to submit a bug report to Unity. And again, I'm really sorry this isn't working for you!

**Comment by tonygod** [comment]
I cannot actually find any crash logs in the location that the editor.log says there should be crash logs.  I will file a Unity bug and see what happens.  Bummer I can't get it to work, but no worries, I am sure it will eventually get sorted out.

**Comment by tonygod** [comment]
Oops I was looking in the wrong directory for the crash logs.  I found them and looked through them but it appears some DLL is failing to initialize or is missing or something.  I sent in a report.

[MeshDeformCrashLogs.zip](https://github.com/keenanwoodall/Deform/files/3049326/MeshDeformCrashLogs.zip)

**Comment by keenanwoodall** [comment]
Interesting. Keep me posted 👌

**Comment by tonygod** [comment]
fogbugz ID 1143792

**Comment by tonygod** [comment]
The problem does not reproduce when using Burst 1.0.0-preview 6.

**Comment by keenanwoodall** [comment]
Very strange. Hopefully it's fixed again in the next version. In the meantime, thanks for finding an alternate solution!
