### ISSUE TITLE
There's an easier way to install

### ISSUE THREAD

**Issue by andybak** [keenanwoodall/Deform#12]
Just add this to packages.json (just after the "dependencies" line):

`    "com.beans.deform": "https://github.com/keenanwoodall/Deform.git",`

**Comment by keenanwoodall** [comment]
While that is probably the easiest way, the reason I didn't include it in the documentation is because it won't update without removing and readding the line in the manifest. Once UPM has better support for linking directly to git repos I'll definitely add it tho!

**Comment by keenanwoodall** [comment]
I ended up changing the documentation to use this install method. Someone said the way I was doing it would create a git submodule. You had the right idea all along 👍

**Comment by warlokkz** [comment]
Hi! I know this is a closed issue, but I ran into an issue related to installing dependencies from git. An SSL issue can appear with a bad configuration in git. I was receiving an error along the lines of the one's in this [thread](https://github.com/glennhickey/progressiveCactus/issues/93). 

Ultimately what fixed the issue for me was updating my git config with:
`git config --global --add http.sslVersion tlsv1.2`

Hope this helps. Also thanks for your work on the project! :^)
