### ISSUE TITLE
OBJ export is broken on locales with comma instead of dot

### ISSUE THREAD

**Issue by hybridherbst** [keenanwoodall/Deform#17]
Steps to reproduce:
- create Sphere object
- add Deformable
- press "Export OBJ" in little Deformable menu
- note that Unity throws an import error
- see the obj file in Windows 3D Viewer:
![image](https://user-images.githubusercontent.com/2693840/60775045-a7a14b80-a11d-11e9-858e-4aec1eb8a321.png)

Expected: sphere exports as sphere and is able to re-import in Unity.

Probable cause: exported OBJ is written with current Locale instead of CultureInvariant.

**Comment by keenanwoodall** [comment]
Wow this is a unique problem! As an ignorant American I never considered files needed to be serialized differently based on culture. Is Unity expecting floats to use commas instead of periods (or vice-versa) as a decimal place, or am I misunderstanding the theorized cause?

**Comment by hybridherbst** [comment]
Haha, it's totally not a unique problem. It happens all the time! The whole of Unity's animation system was broken for half a year since someone internally thought it would be a good idea to suddenly switch from "everything is culture invariant" to "everything uses current culture" and their own code wasn't properly written in numerous places.

This is not really an issue with Unity expecting the data in a specific format - files are internationally usually read/written with CultureInvariant settings to prevent such errors. OBJ file format is old & weird and a lot of implementations are wrong / incorrect. Some actually try both "." and "," on deserialization to work around, but most just don't accept "," (which is fine).

The right thing to do for all things file-related is to always serialize/deserialize with CultureInfo.InvariantCulture.
(5.4f).ToString(CultureInfo.InvariantCulture); => 5.4
(5.4f).ToString(); => 5,4 or 5.4
StringBuilder also has that, etc.

As a sidenote, this is a case of "reinventing the wheel might not be the best idea" - there are a lot of fully-featured OBJ serializers, I saw you just took one from the community :).

**Comment by keenanwoodall** [comment]
Good to know, thanks! I'm not sure how to test this, so before I push anything that might not work is this what I need to be doing?
*before*
```cs
var stringBuilder = new StringBuilder ();

stringBuilder.Append ("g ").Append (name).Append ("\n");
foreach (var vertice in mesh.vertices)
	stringBuilder.Append ($"v {-vertice.x} {vertice.y} {vertice.z}\n");
```
*after*
```cs
var stringBuilder = new StringBuilder ();
var invariantNumberFormat = System.Globalization.CultureInfo.InvariantCulture.NumberFormat;

stringBuilder.Append ("g ").Append (name).Append ("\n");
foreach (var vertice in mesh.vertices)
	stringBuilder.Append ($"v {(-vertice.x).ToString(invariantNumberFormat)} {vertice.y.ToString(invariantNumberFormat)} {vertice.z.ToString(invariantNumberFormat)}\n");
```

As long as I add `ToString(invariantNumberFormat)` to any serialized number it should work right? Let me know if I'm missing anything or if there's a good way you know of for me to test my code.

**Comment by hybridherbst** [comment]
While your way should work there are easier / more concise ones:

There are multiple ways:
1) use StringBuilder without string interpolators
```
var culture = System.Globalization.CultureInfo.InvariantCulture; 
...
stringBuilder.AppendFormat(culture, "v {0} {1} {2}\n", -vertice.x, vertice.y, vertice.z);
```
2) use string interpolators with [FormattableString.Invariant](https://stackoverflow.com/questions/33203261/what-is-the-default-culture-for-c-sharp-6-string-interpolation)
```
stringBuilder.Append(System.FormattableString.Invariant($"v {-vertice.x} {vertice.y} {vertice.z}\n"));
```

I would recommend the first as string interpolators aren't really meant for building large strings, [performance wise](https://koukia.ca/c-string-interpolation-performance-test-73ae6ab27276).

Testing is easy: just change the locale of your machine to German or any other country with comma as number separator. ("Regional Format" in windows settings)

**Comment by keenanwoodall** [comment]
Thanks for the info. This is all very helpful. I'll see if I can push a fix today 👍

**Comment by keenanwoodall** [comment]
Oddly the only options I have are English? I'm not sure what the significance of the countries within the parentheses are because with the "Country or region" set to "Germany" and the Regional format set to "English (Germany)" I printed `Debug.Log (System.Globalization.CultureInfo.CurrentCulture.DisplayName);` and it printed "English (United States)"

My clock is showing 24 hour time instead of 12, an image's size is shown as 1,67MB instead of 1.67MB, there's a button to switch to a German keyboard on my Windows toolbar and I restarted Unity and my PC so my computer definitely registered the change. I'm not really sure what's happening.
 
![2019-07-08_15-14-48](https://user-images.githubusercontent.com/9631530/60839603-28e6f580-a193-11e9-88a0-3fecaaba80ce.gif)

[edit] It looks like this may be specific to Unity. When I try and change the position of a transform in the inspector and use a comma as the decimal place it is converted to a period. If I open the Windows Calculator app it *does* use a comma. However that doesn't explain why `CurrentCulture.DisplayName)` is printing "English (United States)" to the console.
![2019-07-08_16-06-52](https://user-images.githubusercontent.com/9631530/60842733-6ac76a00-a19a-11e9-857f-058d57752ee8.gif)

**Comment by hybridherbst** [comment]
Which Unity version are you using for testing? Also, .NET 3 or .NET 4? Mono/IL2CPP? Some combinations make Unity override the culture (which is the old behaviour). Recent versions should work though.

**Comment by keenanwoodall** [comment]
At the moment of typing this I'm on on the newest official release of Unity. (2019.1.9f1, .NET 4.x Equivalent, Mono and .NET Standard 2.0). I read through this [forum post](https://forum.unity.com/threads/editor-is-using-windows-locale-settings.442847/) and it seems like there's a lot of back and forth on whether it's fixed or not. The last post from around a month ago is someone saying it isn't fixed. I'm just gonna push my changes to [develop](https://github.com/keenanwoodall/Deform/tree/develop). If you know of a combination that will result in Unity detecting the correct culture let me know. In the meantime you can pull the [develop](https://github.com/keenanwoodall/Deform/tree/develop) branch and see if my changes work. I assumed integers don't need culture invariant formatting, but if it's "proper" to always pass the invariant culture to any appending/formatting methods let me know and I'll add it to other the other methods.

**Comment by hybridherbst** [comment]
Well, it just does detect the current culture for me on any 2019.x version.
```
    [ContextMenu("Log Culture")]
    void LogCulture()
    {
        Debug.Log("Current: " + System.Globalization.CultureInfo.CurrentCulture);
        Debug.Log("Current thread: " + System.Threading.Thread.CurrentThread.CurrentCulture);
    }
```
outputs
```
Current: de-DE
Current thread: de-DE
```
for me on 2019.1.6f1, .NET 4.x, Mono, .NET Standard 2.0.

And: yes, you should always use CultureInvariant formatting, even integers are written differently in different cultures (e.g. 1,000,000 vs 1000000 vs 1.000.000). [See this](https://stackoverflow.com/a/28772774)

**Comment by keenanwoodall** [comment]
Ok all numbers should be formatted invariantly now. As for the culture detection I really have no idea. I'm seeing other people on forum posts say that the current culture is always invariant for them as well. I tried changing to IL2CPP (some people were saying it was an issue with Mono) and used your test method but still had no luck.

![image](https://user-images.githubusercontent.com/9631530/60925058-3cb05b80-a268-11e9-83f4-1ef37adb6143.png)

I can't find a way of testing right now and [it doesn't look like something Unity is going to fix,](https://issuetracker.unity3d.com/issues/mono-cultureinfo-dot-currentculture-doesent-work) but if you end up trying it out let me know if it works.

**Comment by hybridherbst** [comment]
I think you need to set the "Language" to German first to actually get the Regional Format for German - it will install a Local Experience Pack with that language.
For me it was the same with english/vietnamese: you can only select them as Regional Formats after installing the actual language pack.
I'll test later today.

**Comment by keenanwoodall** [comment]
I downloaded the deutsche experience pack and changed everything to deutsche. Unity still refused to display anything other than periods which is odd to me because I've definitely seen people with commas as decimal places in Unity on Twitter.

At this point, it's not like it can get worse for the other cultures. It didn't work in the first place and now there's a chance it will. That's good enough for me to merge the changes to master. If someone tests this and find out it doesn't work we can reopen the issue and move from there.
