### ISSUE TITLE
Create FFD/Lattice Deformer

### ISSUE THREAD

**Issue by keenanwoodall** [keenanwoodall/Deform#2]
Multiple variations of the deformer with different resolutions is fine (FFD2x2, FFD4x4 etc), but ideally there will be a single deformer that lets you change the number of control points on each axis.

Ideally you can also change the interpolation type.

**Comment by sabresaurus** [comment]
Got a basic lattice deformer working, resolution is configurable and each control point can be individually moved.

https://user-images.githubusercontent.com/17784523/106396608-e3d38580-6400-11eb-8068-596822339202.mov

**Comment by keenanwoodall** [comment]
#44 merged
