### ISSUE TITLE
Bend Deformers only deform certain meshes on mobile devices

### ISSUE THREAD

**Issue by naash** [keenanwoodall/Deform#21]
I am using set of bend deformers whose angles I update in runtime to create a deformation animation sequence. It works fine in editor but on mobile devices, only certain deformable meshes are affected.

- OS: Android / iOS
- Unity: 2019.3b
- Deform version: [e.g 1.0.3]

While this bug was being reproduced on android device, I checked log to find the following error being thrown repeatedly. 

**Cannot copy data as the managed data is invalid** 

While loading the scene with this deformation animation, the build also crashes sometimes.

**Comment by keenanwoodall** [comment]
I recently pushed changes that solve an issue where data was invalid when normals were set to "None" in the mesh's import settings. I went ahead and made a [new release](https://github.com/keenanwoodall/Deform/releases/tag/v1.0.4) with the fix, so let me know if it fixes the bug.
