### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by erengaygusuz** [keenanwoodall/Deform#27]
I use the first option to install this package to Unity. 

**_Install via UPM
Navigate to your project's Packages folder and open the manifest.json file.
Add this line below the "dependencies": { line
"com.beans.deform": "https://github.com/keenanwoodall/Deform.git",
UPM should now install Deform and it's dependencies.
Don't want to use git? Just download and unzip the repository into the Packages folder._**

When I installed this package, I took these errors:

1) Library\PackageCache\com.unity.burst@1.1.2\Runtime\SharedStatic.cs(114,47): error CS0117: 'BurstCompilerService' does not contain a definition for 'GetOrCreateSharedMemory'
2) Library\PackageCache\com.unity.burst@1.1.2\Runtime\BurstCompiler.cs(42,49): error CS0117: 'BurstCompilerService' does not contain a definition for 'SetCurrentExecutionMode'
3) Library\PackageCache\com.unity.burst@1.1.2\Runtime\BurstCompiler.cs(50,83): error CS0117: 'BurstCompilerService' does not contain a definition for 'GetCurrentExecutionMode'

Does anybody help me to fix these errors?

**Comment by keenanwoodall** [comment]
Sorry to hear it isn't working. What version of Unity are you using?

**Comment by erengaygusuz** [comment]
Thanks for your reply. I am using Unity 2019.3.0 a.7.

9 Ara 2019 Pzt 17:58 tarihinde Keenan Woodall <notifications@github.com>
şunu yazdı:

**Comment by keenanwoodall** [comment]
Deform may not work on betas and alphas. It looks like the Burst package throws compiler errors in that version of Unity. Unfortunately if Burst doesn't work on a version of Unity, neither will Deform. Please try Deform in an official release and let me know if it works for you.

**Comment by erengaygusuz** [comment]
Thanks. I'll try and inform you about it.

9 Ara 2019 Pzt 20:47 tarihinde Keenan Woodall <notifications@github.com>
şunu yazdı:
