### ISSUE TITLE
unable to write to mesh

### ISSUE THREAD

**Issue by MartinBerisso3dar** [keenanwoodall/Deform#29]
https://imgur.com/a/FLin4vP

using an fbx, it gave me errors of non writeable mesh, so i copied the mesh out, used that in the explorer, but it still wont take it, what should i do to be able to use your deform plugin in these meshes?
i tried it in the default meshes from unity and they do work

**Comment by keenanwoodall** [comment]
The error says what to do, as well as the Deformable inspector.
![image](https://user-images.githubusercontent.com/9631530/72228151-d0414c80-3569-11ea-9ccf-09faafed3071.png)

---

All you need to do is select the original mesh asset in the Project window and set "Read/Write Enabled" to true in the import settings

![image](https://user-images.githubusercontent.com/9631530/72228196-42b22c80-356a-11ea-8583-3bd16a3fa8cf.png)

**Comment by arme17** [comment]
I also meet the same question,and i push the [Fix it!] button to solve it.
