### ISSUE TITLE
[Request] Bevel

### ISSUE THREAD

**Issue by ad48hp** [keenanwoodall/Deform#52]
Hello.
Could someone try to make a Bevel deformer ?
I would like to use one to make objects look less blocky.
I tried to find some sample scripts, but i don't quite understand them yet.

https://github.com/nepluno/RoundCornerBox
https://answers.unity.com/questions/1007222/round-procedural-square-mesh-corners-c.html
https://stackoverflow.com/questions/50273477/smooth-dynamically-generated-mesh-in-unity

**Comment by keenanwoodall** [comment]
Deform cannot generate geometry, so I'm afraid this is not currently possible.
