### ISSUE TITLE
Triplanar Shader & Deform Plugin

### ISSUE THREAD

**Issue by usernameHed** [keenanwoodall/Deform#59]
Hello! a video is better than words so here it is:
https://youtu.be/hxlDRrMjSiY

As you can see, the Black Noise stay visually still, while the deform plugin apply deformation to the mesh. (it appen when deforming, but if we move or rotate the object without deform, it works fine.
We are using a Trilanar Shader for the Black Noise. We are using shadergraph.

A triplanar shader works by creating three planes along each axis in object space (object space is important). Once we have those we want to render our texture on each of the planes. Then, we project those rendered images onto our object using the normal of the object to map things. 

the question is : how to stick the texture to the surface while deforming the surface with the deform plugin (with a  triplanar shader because whe also need to change some values dynamically)

Here the shader used:
[Shader.zip](https://github.com/keenanwoodall/Deform/files/7258603/Shader.zip)

**Comment by andybak** [comment]
Not to preempt Keenan but it strikes me that Triplanar is the wrong tool for the job here. The behaviour you're complaining about is the defining character of a triplanar shader. That's what they do. 

Instead you probably want to add a post-processing step after deform to assign UV coords in an approximation of how triplanar works (matching it exactly would be very tricky - you'd probably have to settle for seams at the triangle level)

**Comment by usernameHed** [comment]
Using UV is not possible for us unfortunatly :/ we are thinking of a way to make it work (even partially) without UV.

In blender it is possible to solve this problem by using the Generated output of the Texture Coordinate node

https://docs.blender.org/manual/en/latest/render/shader_nodes/input/texture_coordinate.html

so is it possible to reproduce this node in Unity?

**Comment by andybak** [comment]
> 
> 
> Using UV is not possible for us unfortunatly :/ we are thinking of a way to make it work (even partially) without UV.
> 
> In blender it is possible to solve this problem by using the Generated output of the Texture Coordinate node
> 
> https://docs.blender.org/manual/en/latest/render/shader_nodes/input/texture_coordinate.html
> 
> so is it possible to reproduce this node in Unity?

I guess the equivalent in Unity would be to store the worldspace coordinates BEFORE deform has been run and use those in the triplanar shader.

But you can't do it all in an actual Unity shader because by that point it's too late. You need to do some calculations in C# (or maybe a compute shader) prior to hitting the Unity material shader.

**Comment by keenanwoodall** [comment]
Thanks for hoppin in, @andybak - I agree. I would recommend storing the original/undeformed vertex position in the vertex color or a uv channel for use by your shader. You could write a tool to do this in your modeling program, or write some editor code in Unity to automate the process on import.

To test, here's a simple asset post processor I wrote that saves the object-space vertex position to the vertex color when a model is imported into Unity. (I would be hesitant to use this unmodified in a large project, just posting it in case it helps!)
```cs
public class VertexColorModelPostProcessor : AssetPostprocessor
{
    private void OnPostprocessModel(GameObject g)
    {
        var meshFilters = g.GetComponentsInChildren<MeshFilter>();
        foreach (var meshFilter in meshFilters)
        {
            CopyPositionToColorFor(meshFilter);
        }
    }

    private void CopyPositionToColorFor(MeshFilter mf)
    {
        Mesh mesh = mf.sharedMesh;
        Vector3[] vertices = mesh.vertices;
        Color[] colors = new Color[vertices.Length];

        for (int i = 0; i < vertices.Length; i++)
        {
            var v = vertices[i];
            colors[i] = new Color(v.x, v.y, v.z, 0f);
        }

        mesh.colors = colors;
    }
}
```
