### ISSUE TITLE
Blend Deformable

### ISSUE THREAD

**Issue by BestGamesForever** [keenanwoodall/Deform#61]
Hello it say i need to reference Cache (vertex cache).
How can i find it or create it? i dont what that even means. Can you help me out please?

**Comment by keenanwoodall** [comment]
Ah yea the blend deformer is a bit weird. Select the deformable you want to cache the vertices of, then go to Assets/Create/Deform/Vertex Cache which will create a Vertex Cache asset based on your selected deformable.

![ZNxs6TCuDU](https://user-images.githubusercontent.com/9631530/136671097-d8542576-6575-43f5-8725-a20089908b84.gif)
