### ISSUE TITLE
Deform handlers are not visible in Unity 2021.2.x with Gizmos enabled

### ISSUE THREAD

**Issue by novavision** [keenanwoodall/Deform#63]
**Describe the bug**
In Unity 2021.2.x deformer handlers not shown in Scene window when Gizmos enabled

**To Reproduce**
1. Just install the package in empty Unity 2021.2.x project and try deformer component
2. Turn On Gizmos in Scene window

**Expected behavior**
Handlers are shown

**Screenshots**
![image](https://user-images.githubusercontent.com/5512405/144701872-08c55369-7888-49bb-b56a-79aab66f5d57.png)

- OS: MacOSx 11.6
- Unity: 2021.2.2f1
- Deform version: 1.2.1

**Additional note**
Same issue existed on LeanTouch asset. It was fixed by developer, and he said something was changed on Unity side in 2021.2.x

**Comment by keenanwoodall** [comment]
Hmm, it seems to be working for me on 2021.2.5. What's minor version are you on?
![zxdz0vOfHv](https://user-images.githubusercontent.com/9631530/144751416-61066f4a-fffe-420f-bd00-7215030c66c0.gif)

**Comment by novavision** [comment]
Hm, seems the changes/fixed something in next versions.
I am on Unity: 2021.2.2f1

Tried 2021.2.5 and can confirm the issue doesn't exist there

**Comment by keenanwoodall** [comment]
Ok, great. Since it appears to be an issue with Unity that's fixed in a new minor release I'll mark this as resolved
