### ISSUE TITLE
Deformer are destroyed on play

### ISSUE THREAD

**Issue by novavision** [keenanwoodall/Deform#65]
**Describe the bug**
I am a bit confused, why this happens but in my project (even in empty scene) deformer objects and deformable components are destroyed just after hitting "Play". I check it in completely empty project in different Unity versions and this doesn't happen. 
I checked the code, and found `[PostProcessScene]` attribute before `OnPostprocessScene` method in `DeformBuildPostProcessor` class.  So, there are 2 questions:
1. what the reason to destroy components on Play? Doesn't Deform plugin work runtime?
2. why it not being destroyed in completely empty projects?

**To Reproduce**
Well, as mentioned, I found this behaviour only in my project. Hard to say what exactly could cause it.

**Expected behavior**
Deformable components and deformers objects not being destroyed

- OS: OSx 11.6
- Unity: 2021.2.5
- Deform version: 1.2.1

**Comment by novavision** [comment]
Oh.. that's because stripping settings of Deform plugin... Seems by some reason it was set to "Strip"

**Comment by keenanwoodall** [comment]
That's definitely confusing. I'll modify the behavior to log a message so that it's surfaced to the user when it happens. I just tried installing the package in a fresh package and "Strip" wasn't the default, but if you see it happen again without your input let me know.
