### ISSUE TITLE
Shading breaks

### ISSUE THREAD

**Issue by KenneyNL** [keenanwoodall/Deform#67]
Hey, is it known that shading is broken when a deformer has been added to a mesh? On the left the original mesh, on the right when a deformer has been added.

![shading](https://user-images.githubusercontent.com/6953026/149148544-479dea60-897d-4394-a2d1-25a985ff2d1f.png)

**Comment by keenanwoodall** [comment]
Yes this is a [known limitation.](https://github.com/keenanwoodall/Deform/issues/16) 

Deform recalculates normals the same way as Unity's `Mesh.RecalculateNormals`, albeit multithreaded. Deform/Unity's runtime normal calculation is actually different from the high-quality normal calculation Unity uses in a mesh's import settings. There's more info [here](http://schemingdeveloper.com/2014/10/17/better-method-recalculate-normals-unity/), but the tldr is: it's very expensive to calculate smooth normals for **split vertices** at runtime, so split vertices will result in a hard edge. However I understand the expectation for normals to remain unchanged and this a very common/reasonable request, so it's something I'd like to solve - even if it's recommend to weld split verts where you want a smooth edge.

**Comment by keenanwoodall** [comment]
Gave smoothing angle support another go and seem to have gotten it working. Have done minimal testing, but you can add the package via this url if you want to give it a try
`https://github.com/keenanwoodall/Deform.git#feature/smooth-normals`
![Unity_CzufGKlt6B](https://user-images.githubusercontent.com/9631530/149371236-ae1e8d72-a808-4a51-af3c-db2701ce8dbc.gif)

Closing this issue and will post any updates at #16

**Comment by KenneyNL** [comment]
Oh wow, that's amazing - thanks a lot for picking this up! I'll give it a go and report back on my findings. Again - thank you!
