### ISSUE TITLE
Undo always crashes the Unity

### ISSUE THREAD

**Issue by novavision** [keenanwoodall/Deform#68]
**Describe the bug**
Each time I use Undo while any of Deform component selected, Unity Editor crashes on Windows 11

**To Reproduce**
1. Create Deformable
2. Add any deformer
3. select Deformable 
4. Tap Undo => crash

**Expected behavior**
Undo do what it should, or at least do nothing and don't crash the editor

**Screenshots**

- OS: Windows 11
- Unity: 2021.2.8
- Deform version: 1.2.1

**Comment by keenanwoodall** [comment]
Thanks for the report - I was able to repro on 2021.2.X
This [tracked issue](https://issuetracker.unity3d.com/issues/crash-with-transform-initializetransformhierarchyrecursive-when-using-undo-after-swapping-prefabs) seems to line up with what we're seeing. It mentions the same function at the top of the callstack and the crash happens after undoing on the same Editor versions.
I tried to repro on 2021.1.X and 2022.1.X and the crash went away so I think the 2021.2 crashing is likely something on Unity's end that they need to fix. In the meantime it seems other Editor versions will have to do.
