### ISSUE TITLE
Object with a lattice deformable are incorrectly translated in the world

### ISSUE THREAD

**Issue by rlalance** [keenanwoodall/Deform#75]
**Describe the bug**
After applying a lattice deformer and worked with the control points, an object that looks good in editor mode will get positioned incorrectly in playmode.

**To Reproduce**
1. Apply a Lattice deform on a rock with 4 LODs
2. Answer yes to all in the questions regarding the LOD
3. Modify the controls points
4. Apply scale to the lattice deform
5. Run playmode.
6. Result: The object is moved way into the distance

**Expected behavior**
Object should look the same between edit mode and play mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/1323032/206944303-847f55e3-0e62-4a3b-90be-be3fecb7da74.png)
![image](https://user-images.githubusercontent.com/1323032/206944327-4b0f1fdd-9b31-4cd0-aa3d-21e737f7c9bf.png)
![image](https://user-images.githubusercontent.com/1323032/206944346-9af65092-f58f-480a-988b-1bf671167654.png)

And result which is wrong:
![image](https://user-images.githubusercontent.com/1323032/206944463-65bd3b0c-f460-4900-bd4f-5c218e4450fa.png)
![image](https://user-images.githubusercontent.com/1323032/206944543-215152f0-ecc5-4c06-b3a3-6eb1e06fc6f4.png)

- OS:  Windows 10
- Unity: 2021.3.11f1
- Deform version: 1.2.1]

**Additional context**
Once this feature is working probably, i'm going to use this throughout my level.
Please contact me as I am interested in funding the completion of this deformable lattice.

**Comment by keenanwoodall** [comment]
Sorry to hear about that. I tried going through your steps, but have been unable to reproduce the bug. Would it be possible for you to zip me a repro project?

**Comment by rlalance** [comment]
Certainly!

**Comment by rlalance** [comment]
Just realised, the console had errors in it regarding read/write. I thought I had press the FIX IT button...

![image](https://user-images.githubusercontent.com/1323032/207763738-840f3320-2af1-499a-b0ee-3888ff59afa0.png)

And I can't seem to be able to locate Combined Mesh in my project.. :(

**Comment by rlalance** [comment]
Yup, I have read/write on all my rock meshes.

**Comment by rlalance** [comment]
@keenanwoodall Going to try with other rocks.
When I tried to package the scene, everything came in, so i'm not sure how to send you just the buggy rock.

**Comment by keenanwoodall** [comment]
> Just realised, the console had errors in it regarding read/write. I thought I had press the FIX IT button...
> 
> ![image](https://user-images.githubusercontent.com/1323032/207763738-840f3320-2af1-499a-b0ee-3888ff59afa0.png)
> 
> And I can't seem to be able to locate Combined Mesh in my project.. :(

The errors in the console indicate the game-object is statically batched. Unity is combining all the static game-objects into one mesh when you enter play-mode or make a build and the Deformable cannot read/write to that mesh.

**Comment by keenanwoodall** [comment]
Each game-object has static flags for different things. If you check the static toggle on you turn on all static flags, but you can specifically disable static batching to fix the error.
![image](https://user-images.githubusercontent.com/9631530/208528857-5c35a687-14ad-4c66-b8ff-1dff6ec857ea.png)

That being said, I think the optimal way for Deform to handle this would be for the Deformable to detect if it is on a statically batched game-object and disable/remove itself automatically. I will look into adding this functionality.

**Comment by keenanwoodall** [comment]
This problem is a symptom of a larger problem which is that Deform does not have a proper controls for Deformable stripping. I ended up making a new [feature branch](https://github.com/keenanwoodall/Deform/tree/feature/stripping) that adds a "Strip Mode" parameter to Deformable components. This parameter is forced on when static batching is enabled on a game-object
![image](https://user-images.githubusercontent.com/9631530/208542950-3a169555-0bdf-4789-a45b-7eefb247e497.png)

Let me know if this works for you! It should also solve the issue of meshes getting teleported as that was caused by static batching

**Comment by rlalance** [comment]
OH really!!! This is great!! Will try that ASAP.

**Comment by rlalance** [comment]
Umm, ok, I have one more error to solve and that should be it.
I think you can close this for now.

Thank you @keenanwoodall

**Comment by keenanwoodall** [comment]
Sounds good, thanks for finding this issue!
