### ISSUE TITLE
After removing from project, my physics are different?

### ISSUE THREAD

**Issue by Blurbss** [keenanwoodall/Deform#78]
Sorry to be so vague, but I was playing with deform in my project, then decided it wasn't what I needed. After deleting from my assets, it seems my physics have changed somewhere along the way? Forces applied to objects in my game are now way stronger, and the forces themselves havent changed, nor the mass of the objects. Feels like a value for gravity got messed up somewhere. I've checked and gravity is still -9.81.

Any help?

**Comment by keenanwoodall** [comment]
I'm not sure what that could be I'm sorry. The only physics-related thing Deform does is optionally update a mesh collider to match the deformed mesh. Are you using version control? If not, perhaps you could make a new blank project and copy your Assets folder into it to see if its related to project settings
