### ISSUE TITLE
Access Lattice Points via Script

### ISSUE THREAD

**Issue by YuuZena** [keenanwoodall/Deform#81]
Hey together!

I'm pretty new to this Asset and I would need to access the Lattice Points via a Script.

![image](https://github.com/keenanwoodall/Deform/assets/140416359/675e7d17-3bae-4d25-8612-9991b024f709)

I want to deform the Object during gameplay so it will always fit with the environment. 

regards
YuuZena

**Comment by keenanwoodall** [comment]
`LatticeDeformer` exposes `GetControlPoint` and `SetControlPoint` helper methods as well as a flat `float3[] ControlPoints` array.

Here's an example script that generates game-objects for the control points.
![Unity_uDmXkcS0ge](https://github.com/keenanwoodall/Deform/assets/9631530/b39ccdeb-a218-4ab3-871b-55b61118c642)
```cs
public class SetControlPoints : MonoBehaviour
{
    public LatticeDeformer deformer;

    private Transform[] controlPointAnchors;
    
    private void Start()
    {
        controlPointAnchors = deformer.ControlPoints.Select(p =>
        {
            var newAnchor = GameObject.CreatePrimitive(PrimitiveType.Cube);
            newAnchor.name = "Control Point";
            newAnchor.transform.SetParent(deformer.transform);
            newAnchor.transform.localPosition = p;
            newAnchor.transform.localScale = Vector3.one * 0.1f;
            return newAnchor.transform;
        }).ToArray();
    }

    private void Update()
    {
        for (var i = 0; i < controlPointAnchors.Length; i++)
        {
            var anchor = controlPointAnchors[i];
            if (!anchor.hasChanged)
                continue;
            anchor.hasChanged = false;
            deformer.ControlPoints[i] = deformer.transform.InverseTransformPoint(anchor.position);
        }
    }
}
```

**Comment by YuuZena** [comment]
Thanks for that! It works very well. 👍 

I was thinking if it would be possible to have a smoother Deformation. Currently everything is Linear, Point to Point.

![image](https://github.com/keenanwoodall/Deform/assets/140416359/581efc25-ef27-4e49-b7a8-4683df76e95c)


Like a Bezier Curve from Point to Point so the Start and End are tangentially.

regards YuuZena

**Comment by keenanwoodall** [comment]
I just pushed simple hermite smoothing to the develop branch 9b2d71605de8f4a10c07ed068e5bc86e7fe9e15c. 
Here's what simple smooth-step smoothing looks like
![Unity_4VrleIyPgC](https://github.com/keenanwoodall/Deform/assets/9631530/dba397f3-0879-41bc-9ade-8495dea62875)
I think the proper solution would be to do some sort of tricubic interpolation like catmull-rom, but that would be nontrivial :P
