### ISSUE TITLE
About LatticeDeformer.controlPoints

### ISSUE THREAD

**Issue by IwakuraRein** [keenanwoodall/Deform#82]
Just wondering why not allocate the controlPoints a persistent NativeArray and use it in the job, instead, allocating everytime?

Incidentally, I am implemeting the spring-mass-damper model with the LatticeDeformer.

**Comment by keenanwoodall** [comment]
The LatticeDeformer was actually written by a contributor so I'm not sure the motivation; perhaps just convenience. If you see any performance problems in your use-case I can pull it out into a persistent array, otherwise I'll leave it be for now.
