### ISSUE TITLE
Add ability to control a deformer's transform from a deformable's list

### ISSUE THREAD

**Issue by keenanwoodall** [keenanwoodall/Deform#9]
The transform handles shouldn't get in the way of the deformable's transform handles. Controls could exist for the deformer *and* deformable, but a toggle between the two would be acceptable as well.

**Comment by batu** [comment]
First off, thank you very much for this lovely library!

Is there currently a way to dynamically add new deformers to a deformable?

I am prototyping an interaction where you fly around and transform the space around you but I only want to have the meshes close to my character to be checking for a deformation, in addition to the ability to "drop" a deformer and create a new one.

Here is an idea of how it looks:
https://twitter.com/BatuAytemiz/status/1115077117312552960

**Comment by keenanwoodall** [comment]
Closing all my "todo" issues that have been around forever. They don't need to be issues
